export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_AVAILABILITY_SUCCESS = 'LOAD_AVAILABILITY_SUCCESS';
export const EDIT_SEATS_LEFT = 'EDIT_SEATS_LEFT';
export const REDUCE_SEATS_LEFT = 'REDUCE_SEATS_LEFT'; 